[template]
cargo_generate_version = ">=0.17.4"
ignore = [".git", "LICENSE-APACHE", "LICENSE-MIT", "README.md"]

[hooks]
pre = ["pre-script.rhai"]

[placeholders.linux]
prompt = "Add support for Linux platform?"
type = "bool"
default = true

[placeholders.esp]
prompt = "Add support for ESP32 platform?"
type = "bool"
default = true

[conditional.'esp'.placeholders.mcu]
prompt = "Which ESP MCU to target?"
type = "string"
choices = [
  "esp32",
  "esp32c2",
  "esp32c3",
  "esp32c6",
  "esp32h2",
  "esp32s2",
  "esp32s3",
]
default = "esp32"

[conditional.'!esp']
ignore = ["build.rs", "partitions.csv", "sdkconfig.defaults", "espflash.toml"]

[placeholders.template]
prompt = "Initialize template code for project?"
type = "bool"
default = true

[conditional.'template'.placeholders.template_advanced]
prompt = "Configure advanced template options?"
type = "bool"
default = false


[conditional.'template_advanced'.placeholders.template_logger]
prompt = "Initialize logger?"
type = "bool"
default = true

[conditional.'template_advanced'.placeholders.template_wifi]
prompt = "Setup WiFi provisioning?"
type = "bool"
default = true
